services:
  db:
    image: postgres:17.2
    volumes: 
     - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
  api:
    image: ghcr.io/codaea/shortener:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      GIN_MODE: release
